FROM ubuntu:16.04
MAINTAINER Gareth Rushgrove "gareth@puppet.com"

ENV PUPPET_AGENT_VERSION="1.5.0" \
    R10K_VERSION="2.2.2" \
    UBUNTU_CODENAME="xenial"

PUPPET_INSTALL
PUPPET_COPY_PUPPETFILE
PUPPET_COPY_MANIFESTS bob
PUPPET_RUN
EXPOSE 80

CMD ["nginx"]
